=== gbif/ipt/deprecated/ipt-1.0-RC3/resources/thesaurus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://data.gbif.org/thesaurus"
	xmlns:dc="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="http://data.gbif.org/thesaurus"
	elementFormDefault="qualified">
	<xs:import namespace="http://purl.org/dc/terms/"
		schemaLocation="dc.xsd" />
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd" />
	<xs:element name="thesaurus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="concept" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required" />
			<xs:attribute ref="dc:title" use="required" />
			<xs:attribute ref="dc:description" use="optional">
				<xs:annotation>
					<xs:documentation>A URL acting as documentation for the entire
						vocabulary</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="numConcepts" use="optional"
				type="xs:positiveInteger" />

		</xs:complexType>
	</xs:element>
	<xs:element name="concept">
		<xs:complexType>

			<xs:sequence>
				<!-- Many titles per language for synonyms -->
				<xs:element name="preferred">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded"
								minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- Many titles per language for synonyms -->
				<xs:element name="alternative">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded"
								minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required">
				<xs:annotation>
					<xs:documentation>The proper full URI. Preferably pointing to an
						RDF document in an ontology</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional">
				<xs:annotation>
					<xs:documentation>A URL acting as documentation of the concept
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:identifier" use="required">
				<xs:annotation>
					<xs:documentation>A short code locally unique within a vocabulary
						as identified by the dc:type attribute.
						Should be language neutral as much as possible. E.g. DE for Germany or
						familia for the family rank</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:issued" use="required" />
			<xs:anyAttribute processContents="lax" />
		</xs:complexType>
	</xs:element>
	<xs:element name="term">
		<xs:complexType>
			<xs:attribute ref="dc:title" use="required">
				<xs:annotation>
					<xs:documentation>The term itself</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang" use="required" />
			<xs:attribute ref="dc:source" use="required">
				<xs:annotation>
					<xs:documentation>The source where the term originated from
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:modified" use="required" />
			<xs:anyAttribute processContents="lax" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gbif/ipt/src/test/resources/thesauri/agent_role.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus
  dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole"
  dc:description="Vocabulary for agent roles used in EML."
  dc:title="EML Agent Role Vocabulary"
  xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
  <concept dc:identifier="author" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/author"
           dc:relation=""
           dc:description="an agent who is an author of a publication that used the dataset, or author of a data paper">
    <preferred>
      <term dc:title="Author" xml:lang="en"/>
      <term dc:title="Autor" xml:lang="es"/>
      <term dc:title="Auteur" xml:lang="fr"/>
      <term dc:title="作者" xml:lang="zh"/>
      <term dc:title="Autor" xml:lang="pt"/>
      <term dc:title="論文著者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="contentProvider" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/contentProvider"
           dc:relation=""
           dc:description=" an agent who contributed content to a dataset (the dataset being described may be a composite)">
    <preferred>
      <term dc:title="Content Provider" xml:lang="en"/>
      <term dc:title="Proveedor de Contenido" xml:lang="es"/>
      <term dc:title="Fournisseur de Contenu" xml:lang="fr"/>
      <term dc:title="內容提供者" xml:lang="zh"/>
      <term dc:title="Provedor de Conteúdo" xml:lang="pt"/>
      <term dc:title="データ提供者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="custodianSteward" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/custodianSteward"
           dc:relation=""
           dc:description=" an agent who is responsible for/takes care of the dataset">
    <preferred>
      <term dc:title="Custodian Steward" xml:lang="en"/>
      <term dc:title="Custodio de los Datos" xml:lang="es"/>
      <term dc:title="Curateur des Données" xml:lang="fr"/>
      <term dc:title="託管人" xml:lang="zh"/>
      <term dc:title="Custódio de dados" xml:lang="pt"/>
      <term dc:title="custodianSteward(保管者）" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="distributor" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/distributor"
           dc:relation=""
           dc:description="an agent involved in the publishing/distribution chain of a dataset">
    <preferred>
      <term dc:title="Distributor" xml:lang="en"/>
      <term dc:title="Distribuidor" xml:lang="es"/>
      <term dc:title="Distributeur" xml:lang="fr"/>
      <term dc:title="散布者" xml:lang="zh"/>
      <term dc:title="Distribuidor" xml:lang="pt"/>
      <term dc:title="データ配布者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="editor" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/editor"
           dc:relation=""
           dc:description="an agent associated with editing a publication that used the dataset, or a data paper">
    <preferred>
      <term dc:title="Editor" xml:lang="en"/>
      <term dc:title="Editor" xml:lang="es"/>
      <term dc:title="Editeur" xml:lang="fr"/>
      <term dc:title="編輯" xml:lang="zh"/>
      <term dc:title="Editor" xml:lang="pt"/>
      <term dc:title="編集者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="metadataProvider" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/metadataProvider"
           dc:relation=""
           dc:description="an agent responsible for providing the metadata">
    <preferred>
      <term dc:title="Metadata Provider" xml:lang="en"/>
      <term dc:title="Proveedor de los Metadatos" xml:lang="es"/>
      <term dc:title="Fournisseur des Métadonnées" xml:lang="fr"/>
      <term dc:title="元數據提供者" xml:lang="zh"/>
      <term dc:title="Provedor dos Metadados" xml:lang="pt"/>
      <term dc:title="メタデータ提供者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="originator" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/originator"
           dc:relation=""
           dc:description="an agent who originally gathered/prepared the dataset">
    <preferred>
      <term dc:title="Originator" xml:lang="en"/>
      <term dc:title="Originador" xml:lang="es"/>
      <term dc:title="Créateur" xml:lang="fr"/>
      <term dc:title="出處" xml:lang="zh"/>
      <term dc:title="Originador" xml:lang="pt"/>
      <term dc:title="最初のデータ採集者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="owner" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/owner"
           dc:relation=""
           dc:description="an agent who owns the dataset (may or may not be the custodian)">
    <preferred>
      <term dc:title="Owner" xml:lang="en"/>
      <term dc:title="Propietario" xml:lang="es"/>
      <term dc:title="Propriétaire" xml:lang="fr"/>
      <term dc:title="擁有者" xml:lang="zh"/>
      <term dc:title="Proprietário" xml:lang="pt"/>
      <term dc:title="データ所有者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="pointOfContact" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/pointOfContact"
           dc:relation=""
           dc:description="an agent to contact for further information about the dataset">
    <preferred>
      <term dc:title="Point Of Contact" xml:lang="en"/>
      <term dc:title="Punto de Contacto" xml:lang="es"/>
      <term dc:title="Personne de Contact" xml:lang="fr"/>
      <term dc:title="連絡人" xml:lang="zh"/>
      <term dc:title="Ponto de Contato" xml:lang="pt"/>
      <term dc:title="連絡先" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="principalInvestigator"
           dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/principalInvestigator"
           dc:relation=""
           dc:description="a primary scientific contact associated with the dataset">
    <preferred>
      <term dc:title="Principal Investigator" xml:lang="en"/>
      <term dc:title="Investigador Principal" xml:lang="es"/>
      <term dc:title="Chercheur Principal" xml:lang="fr"/>
      <term dc:title="研究主持人" xml:lang="zh"/>
      <term dc:title="Pesquisador Principal" xml:lang="pt"/>
      <term dc:title="研究代表者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="processor" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/processor"
           dc:relation=""
           dc:description="an agent responsible for any post-collection processing of the dataset">
    <preferred>
      <term dc:title="Processor" xml:lang="en"/>
      <term dc:title="Procesador" xml:lang="es"/>
      <term dc:title="Processeur" xml:lang="fr"/>
      <term dc:title="處理者" xml:lang="zh"/>
      <term dc:title="Processador" xml:lang="pt"/>
      <term dc:title="データ処理者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="publisher" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/publisher"
           dc:relation=""
           dc:description="the agent associated with the publishing of some entity (paper, article, book, etc) based on the dataset, or of a data paper">
    <preferred>
      <term dc:title="Publisher" xml:lang="en"/>
      <term dc:title="Publicador" xml:lang="es"/>
      <term dc:title="Publicateur" xml:lang="fr"/>
      <term dc:title="發布者" xml:lang="zh"/>
      <term dc:title="Publicador" xml:lang="pt"/>
      <term dc:title="データ公開者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="user" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/user"
           dc:relation=""
           dc:description="an agent that makes use of the dataset">
    <preferred>
      <term dc:title="User" xml:lang="en"/>
      <term dc:title="Usuario" xml:lang="es"/>
      <term dc:title="Utilisateur" xml:lang="fr"/>
      <term dc:title="使用者" xml:lang="zh"/>
      <term dc:title="Usuário" xml:lang="pt"/>
      <term dc:title="データ利用者" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="programmer" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/programmer"
           dc:relation=""
           dc:description="an agent providing informatics/programming support related to the dataset">
    <preferred>
      <term dc:title="Programmer" xml:lang="en"/>
      <term dc:title="Programador" xml:lang="es"/>
      <term dc:title="Programmeur" xml:lang="fr"/>
      <term dc:title="程式設計師" xml:lang="zh"/>
      <term dc:title="Programador" xml:lang="pt"/>
      <term dc:title="プログラマー" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="curator" dc:URI="http://rs.gbif.org/vocabulary/gbif/agentRole/curator"
           dc:relation=""
           dc:description="an agent that maintains and documents the specimens in a collection. Some of their duties include preparing and labeling specimens so they are ready for identification, and protecting the specimens">
    <preferred>
      <term dc:title="Curator" xml:lang="en"/>
      <term dc:title="Curador" xml:lang="es"/>
      <term dc:title="Conservateur" xml:lang="fr"/>
      <term dc:title="典藏經理" xml:lang="zh"/>
      <term dc:title="Curador" xml:lang="pt"/>
      <term dc:title="キュレーター" xml:lang="ja"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
</thesaurus>

=== gbif/ipt/branches/appfuse-explode/resources/thesauri/dwc-type.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus dc:URI="http://rs.tdwg.org/dwc/dwctype/" dc:description="" dc:title="Darwin Core Type Vocabulary" numConcepts="9" xmlns="http://data.gbif.org/thesaurus" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://data.gbif.org/thesaurus  http://gbrds.gbif.org/resources/schemas/thesaurus.xsd">
 <concept dc:identifier="preservedspecimen" dc:URI="http://rs.tdwg.org/dwc/dwctype/PreservedSpecimen"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Preserved Specimen" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="fossilspecimen" dc:URI="http://rs.tdwg.org/dwc/dwctype/FossilSpecimen"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Fossil Specimen" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="livingspecimen" dc:URI="http://rs.tdwg.org/dwc/dwctype/LivingSpecimen"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Living Specimen" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="humanobservation" dc:URI="http://rs.tdwg.org/dwc/dwctype/HumanObservation"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Human Observation" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="machineobservation" dc:URI="http://rs.tdwg.org/dwc/dwctype/MachineObservation"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Machine Observation" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="stillimage" dc:URI="http://rs.tdwg.org/dwc/dwctype/StillImage"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Still Image" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="movingimage" dc:URI="http://rs.tdwg.org/dwc/dwctype/MovingImage"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Moving Image" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="sound" dc:URI="http://rs.tdwg.org/dwc/dwctype/Sound"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Sound" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="physicalobject" dc:URI="http://rs.tdwg.org/dwc/dwctype/PhysicalObject"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="Physical Object" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
</thesaurus>

=== gbif/ipt/trunk/gbif-ipt/src/test/resources/thesauri/type-vocabulary.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://rs.gbif.org/style/human.xsl"?>
<voc:thesaurus xmlns:voc="http://rs.gbif.org/thesaurus/" xmlns:ext="http://rs.gbif.org/extension/" xmlns:dcam="http://purl.org/dc/dcam/" xmlns:dc="http://purl.org/dc/terms/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd" 
  dc:URI="http://dublincore.org/documents/dcmi-type-vocabulary/"
  dc:relation="http://dublincore.org/documents/dcmi-type-vocabulary/"
  dc:description='The DCMI Type Vocabulary provides a general, cross-domain list of approved terms that may be used as values for the Resource Type element to identify the genre of a resource. The terms documented here are also included in the more comprehensive document "DCMI Metadata Terms" at http://dublincore.org/documents/dcmi-terms/.' 
  dc:title="Dublin Core Type Vocabulary" 
  >
  <voc:concept dc:identifier="Collection" dc:URI="http://purl.org/dc/dcmitype/Collection" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Collection" xml:lang="eng"/>
    <voc:term dc:title="Sammlung" xml:lang="ger"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="Dataset" dc:URI="http://purl.org/dc/dcmitype/Dataset" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Dataset" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="Event" dc:URI="http://purl.org/dc/dcmitype/Event" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Event" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="Image" dc:URI="http://purl.org/dc/dcmitype/Image" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Image" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="InteractiveResource" dc:URI="http://purl.org/dc/dcmitype/InteractiveResource" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Interactive Resource" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="Service" dc:URI="http://purl.org/dc/dcmitype/Service" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Service" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="Software" dc:URI="http://purl.org/dc/dcmitype/Software" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Software" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="Sound" dc:URI="http://purl.org/dc/dcmitype/Sound" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Sound" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="Text" dc:URI="http://purl.org/dc/dcmitype/Text" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Text" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="PhysicalObject" dc:URI="http://purl.org/dc/dcmitype/PhysicalObject" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Physical Object" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="StillImage" dc:URI="http://purl.org/dc/dcmitype/StillImage" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Still Image" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
  <voc:concept dc:identifier="MovingImage" dc:URI="http://purl.org/dc/dcmitype/MovingImage" >
   <voc:preferred>
    <voc:term dc:source="Dublin Core RDF" dc:title="Moving Image" xml:lang="en"/>
   </voc:preferred>
   <voc:alternative/>
  </voc:concept>
 </voc:thesaurus>
