=== gbif/ipt/deprecated/ipt-1.0-RC3/resources/thesaurus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://data.gbif.org/thesaurus"
	xmlns:dc="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/"
	xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="http://data.gbif.org/thesaurus"
	elementFormDefault="qualified">
	<xs:import namespace="http://purl.org/dc/terms/"
		schemaLocation="dc.xsd" />
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd" />
	<xs:element name="thesaurus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="concept" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required" />
			<xs:attribute ref="dc:title" use="required" />
			<xs:attribute ref="dc:description" use="optional">
				<xs:annotation>
					<xs:documentation>A URL acting as documentation for the entire
						vocabulary</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="numConcepts" use="optional"
				type="xs:positiveInteger" />

		</xs:complexType>
	</xs:element>
	<xs:element name="concept">
		<xs:complexType>

			<xs:sequence>
				<!-- Many titles per language for synonyms -->
				<xs:element name="preferred">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded"
								minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<!-- Many titles per language for synonyms -->
				<xs:element name="alternative">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="term" maxOccurs="unbounded"
								minOccurs="0" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="dc:URI" use="required">
				<xs:annotation>
					<xs:documentation>The proper full URI. Preferably pointing to an
						RDF document in an ontology</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:description" use="optional">
				<xs:annotation>
					<xs:documentation>A URL acting as documentation of the concept
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:identifier" use="required">
				<xs:annotation>
					<xs:documentation>A short code locally unique within a vocabulary
						as identified by the dc:type attribute.
						Should be language neutral as much as possible. E.g. DE for Germany or
						familia for the family rank</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:issued" use="required" />
			<xs:anyAttribute processContents="lax" />
		</xs:complexType>
	</xs:element>
	<xs:element name="term">
		<xs:complexType>
			<xs:attribute ref="dc:title" use="required">
				<xs:annotation>
					<xs:documentation>The term itself</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="xml:lang" use="required" />
			<xs:attribute ref="dc:source" use="required">
				<xs:annotation>
					<xs:documentation>The source where the term originated from
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute ref="dc:modified" use="required" />
			<xs:anyAttribute processContents="lax" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gbif/ipt/branches/appfuse-explode/resources/thesauri/gisin-abundance.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus dc:URI="http://rs.tdwg.org/dwc/dwctype/" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=5" dc:title="Darwin Core Type Vocabulary" xmlns="http://data.gbif.org/thesaurus" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://data.gbif.org/thesaurus  http://gbrds.gbif.org/resources/schemas/thesaurus.xsd">
 
 <concept dc:identifier="Common" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Common" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=5" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Common" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Dominant" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Dominant" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=5" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Dominant" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Monoculture" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Monoculture" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=5" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Monoculture" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Rare" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Rare" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=5" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Rare" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Unknown" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Unknown" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=5" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Unknown" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Zero" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Zero" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=5" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Zero" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>

</thesaurus>

=== gbif/ipt/trunk/gbif-providertool/resources/thesauri/gisin-distribution.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus dc:URI="http://rs.tdwg.org/dwc/dwctype/" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=4" dc:title="Darwin Core Type Vocabulary" xmlns="http://data.gbif.org/thesaurus" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://data.gbif.org/thesaurus  http://gbrds.gbif.org/resources/schemas/thesaurus.xsd">

 <concept dc:identifier="Unknown" dc:URI="http://www.gisinetwork.org/IASProfile/Distribution/terms/Unknown" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=4" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Unknown" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Localized" dc:URI="http://www.gisinetwork.org/IASProfile/Distribution/terms/Localized" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=4" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Localized" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Moderate" dc:URI="http://www.gisinetwork.org/IASProfile/Distribution/terms/Moderate" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=4" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Moderate" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Widespread" dc:URI="http://www.gisinetwork.org/IASProfile/Distribution/terms/Widespread" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=4" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Widespread" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
</thesaurus>

=== gbif/ipt/branches/gbif-ipt-lite/gbif-providertool/resources/thesauri/gisin-trend.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus dc:URI="http://rs.tdwg.org/dwc/dwctype/" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=6" dc:title="Darwin Core Type Vocabulary" xmlns="http://data.gbif.org/thesaurus" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://data.gbif.org/thesaurus  http://gbrds.gbif.org/resources/schemas/thesaurus.xsd">

 <concept dc:identifier="Name" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Name" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=6" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Name" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Expanding" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Expanding" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=6" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Expanding" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Unknown" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Unknown" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=6" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Unknown" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Declining" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Declining" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=6" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Declining" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Stable" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Stable" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=6" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Stable" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
</thesaurus>

=== gbif/ipt/trunk/gbif-providertool/resources/thesauri/gisin-spreadrate.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus dc:URI="http://rs.tdwg.org/dwc/dwctype/" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=4" dc:title="Darwin Core Type Vocabulary" xmlns="http://data.gbif.org/thesaurus" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://data.gbif.org/thesaurus  http://gbrds.gbif.org/resources/schemas/thesaurus.xsd">

 <concept dc:identifier="Name" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Name" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=7" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Name" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Unknown" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Unknown" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=7" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Unknown" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Slow" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Slow" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=7" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Slow" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Moderate" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Moderate" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=7" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Moderate" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Rapid" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Rapid" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=7" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Rapid" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept> 
 
</thesaurus>

=== gbif/ipt/deprecated/ipt-1.0b.7/gbif-providertool/db/thesaurus_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus xmlns:dc="http://purl.org/dc/terms/"
    xmlns="http://data.gbif.org/thesaurus"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://data.gbif.org/thesaurus  thesaurus.xsd">
    <concept dc:identifier="US" dc:URI="http://iso.org/3166#US" iso3Digit="USA" dc:type="http://purl.org/dc/terms/ISO3166" dc:issued="2006-05-04T18:13:51.0Z">
        <preferred>
            <term dc:title="United States of America" xml:lang="en" dc:source="source0" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Vereinigte Staaten von Amerika" xml:lang="de" dc:source="source1" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </preferred>
        <alternative>
            <term dc:title="USA" xml:lang="en" dc:source="source3" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="US of A" xml:lang="en" dc:source="source4" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="United States" xml:lang="en" dc:source="source5" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </alternative>
    </concept>

    <concept dc:identifier="Species" dc:URI="http://rs.tdwg.org/ontology/voc/TaxonRank#Species" dc:type="http://rs.tdwg.org/ontology/voc/TaxonRank" dc:issued="2006-05-04T18:13:51.0Z">
        <preferred>
            <term dc:title="Species" xml:lang="en" dc:source="source12" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Art" xml:lang="de" dc:source="source13" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </preferred>
        <alternative>
            <term dc:title="Spec." xml:lang="en" dc:source="source15" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Sp." xml:lang="en" dc:source="source16" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Spec" xml:lang="en" dc:source="source17" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </alternative>
    </concept>
    
    <concept dc:identifier="en" dc:URI="http:/iso.org/iso639-1#en" dc:type="http://purl.org/dc/terms/ISO639-3" dc:issued="2006-05-04T18:13:51.0Z">
        <preferred>
            <term dc:title="English" xml:lang="en" dc:source="source12" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Englisch" xml:lang="de" dc:source="source13" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </preferred>
        <alternative/>        
    </concept>
</thesaurus>

=== gbif/ipt/src/test/resources/thesauri/update_frequency.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/style/human.xsl"?>
<thesaurus
  dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency"
  dc:description="Vocabulary that describes the frequency with which changes and additions are made to the dataset after the initial dataset is completed. The vocabulary is derived from the EML specification (version 2.1.1) at http://knb.ecoinformatics.org/software/eml/eml-2.1.1/eml-dataset.html#maintenanceUpdateFrequency/."
  dc:title="EML Maintenance Update Frequency"
  xmlns="http://rs.gbif.org/thesaurus/" xmlns:dc="http://purl.org/dc/terms/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://rs.gbif.org/thesaurus/  http://rs.gbif.org/schema/thesaurus.xsd">
  <concept dc:identifier="daily" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/daily"
           dc:relation=""
           dc:description="Updated 1 time each day.">
    <preferred>
      <term dc:title="Daily" xml:lang="en"/>
      <term dc:title="Diario" xml:lang="es"/>
      <term dc:title="Journalière" xml:lang="fr"/>
      <term dc:title="Diariamente" xml:lang="pt"/>
      <term dc:title="每日一次" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="weekly" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/weekly"
           dc:relation=""
           dc:description="Updated 1 time each week.">
    <preferred>
      <term dc:title="Weekly" xml:lang="en"/>
      <term dc:title="Semanal" xml:lang="es"/>
      <term dc:title="Quotidienne" xml:lang="fr"/>
      <term dc:title="Semanalmente" xml:lang="pt"/>
      <term dc:title="每周一次" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="monthly" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/monthly"
           dc:relation=""
           dc:description="Updated 1 time each month.">
    <preferred>
      <term dc:title="Monthly" xml:lang="en"/>
      <term dc:title="Mensual" xml:lang="es"/>
      <term dc:title="Mensuel" xml:lang="fr"/>
      <term dc:title="Mensalmente" xml:lang="pt"/>
      <term dc:title="每月一次" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="biannually" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/biannually"
           dc:relation=""
           dc:description="Updated 2 times each year.">
    <preferred>
      <term dc:title="Biannually" xml:lang="en"/>
      <term dc:title="Semestral" xml:lang="es"/>
      <term dc:title="Bi-annuel" xml:lang="fr"/>
      <term dc:title="Bianual" xml:lang="pt"/>
      <term dc:title="兩年一次" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="annually" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/annually"
           dc:relation=""
           dc:description="Updated 1 time each year.">
    <preferred>
      <term dc:title="Annually" xml:lang="en"/>
      <term dc:title="Annual" xml:lang="es"/>
      <term dc:title="Annuel" xml:lang="fr"/>
      <term dc:title="Atualmente" xml:lang="pt"/>
      <term dc:title="每年一次" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="asNeeded" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/asNeeded"
           dc:relation=""
           dc:description="Updated as needed.">
    <preferred>
      <term dc:title="As needed" xml:lang="en"/>
      <term dc:title="Cuando sea necesario" xml:lang="es"/>
      <term dc:title="Quand cela est nécessaire" xml:lang="fr"/>
      <term dc:title="Quando necessário" xml:lang="pt"/>
      <term dc:title="需要時" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="continually" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/continually"
           dc:relation=""
           dc:description="Updated continually.">
    <preferred>
      <term dc:title="Continually" xml:lang="en"/>
      <term dc:title="Continuo" xml:lang="es"/>
      <term dc:title="Continuellement" xml:lang="fr"/>
      <term dc:title="Continuamente" xml:lang="pt"/>
      <term dc:title="持續更新" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="irregular" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/irregular"
           dc:relation=""
           dc:description="Updated at irregular intervals.">
    <preferred>
      <term dc:title="Irregular" xml:lang="en"/>
      <term dc:title="Irregular" xml:lang="es"/>
      <term dc:title="Irrègulière" xml:lang="fr"/>
      <term dc:title="Irregular" xml:lang="pt"/>
      <term dc:title="依其他週期更新" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="notPlanned" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/notPlanned"
           dc:relation=""
           dc:description="Further updates are not planned.">
    <preferred>
      <term dc:title="Not planned" xml:lang="en"/>
      <term dc:title="No planeado" xml:lang="es"/>
      <term dc:title="Non planifié" xml:lang="fr"/>
      <term dc:title="Não plenejado" xml:lang="pt"/>
      <term dc:title="無計畫更新" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="unknown" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/unknown"
           dc:relation=""
           dc:description="Further updates may still happen, but it is not known for sure.">
    <preferred>
      <term dc:title="Unknown" xml:lang="en"/>
      <term dc:title="Desconocido" xml:lang="es"/>
      <term dc:title="Inconnue" xml:lang="fr"/>
      <term dc:title="Desconhecido" xml:lang="pt"/>
      <term dc:title="有可能更新，但不確知何時" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
  <concept dc:identifier="otherMaintenancePeriod" dc:URI="http://rs.gbif.org/vocabulary/eml/updateFrequency/otherMaintenancePeriod"
           dc:relation=""
           dc:description="Updated according to some other interval.">
    <preferred>
      <term dc:title="Other maintenance period" xml:lang="en"/>
      <term dc:title="Otro periodo de mantenimiento" xml:lang="es"/>
      <term dc:title="Autre période de maintenance" xml:lang="fr"/>
      <term dc:title="Outro período de manutenção" xml:lang="pt"/>
      <term dc:title="其他更新週期" xml:lang="zh"/>
    </preferred>
    <alternative>
    </alternative>
  </concept>
</thesaurus>

=== gbif/ipt/branches/appfuse-explode/resources/thesauri/gisin-persistence.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus dc:URI="http://rs.tdwg.org/dwc/dwctype/" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=3" dc:title="Darwin Core Type Vocabulary" xmlns="http://data.gbif.org/thesaurus" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://data.gbif.org/thesaurus  http://gbrds.gbif.org/resources/schemas/thesaurus.xsd">

 <concept dc:identifier="Unknown" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Unknown" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=3" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Unknown" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="DiedOut" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/DiedOut" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=3" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="DiedOut" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Transient" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Transient" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=3" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Transient" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Temporary" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Temporary" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=3" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Temporary" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
 <concept dc:identifier="Persistent" dc:URI="http://www.gisinetwork.org/IASProfile/Abundance/terms/Persistent" dc:description="http://www.niiss.org/cwis438/websites/GISINDirectory/tech/Concept_Info.php?ConceptID=3" dc:issued="2009-04-01T01:01:01+00:00">
  <preferred>
   <term dc:modified="2009-01-01T01:01:01+00:00" dc:source="" dc:title="Persistent" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 
</thesaurus>

=== gbif/ipt/branches/ipt-1.0/resources/thesauri/nomenclature-code.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus dc:URI="http://rs.tdwg.org/ontology/voc/TaxonName.rdf#NomenclaturalCodeTerm" dc:description="" dc:title="TDWG Nomenclatural Codes" numConcepts="5" xmlns="http://data.gbif.org/thesaurus" xmlns:dc="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://data.gbif.org/thesaurus  http://gbrds.gbif.org/resources/schemas/thesaurus.xsd">
 <concept dc:identifier="icbn" dc:URI="http://rs.tdwg.org/dwc/dwctype/ICBN"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="ICBN" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="iczn" dc:URI="http://rs.tdwg.org/dwc/dwctype/ICZN"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="ICZN" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="bc" dc:URI="http://rs.tdwg.org/dwc/dwctype/BC"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="BC" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="icncp" dc:URI="http://rs.tdwg.org/dwc/dwctype/ICNCP"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="ICNCP" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
 <concept dc:identifier="biocode" dc:URI="http://rs.tdwg.org/dwc/dwctype/BioCode"  dc:issued="2008-12-17T04:31:07+00:00">
  <preferred>
   <term dc:modified="2008-12-18T04:54:28+00:00" dc:source="" dc:title="BioCode" xml:lang="en"/>
  </preferred>
  <alternative>
  </alternative>
 </concept>
</thesaurus>
