=== gbif/ipt/trunk/gbif-providertool/db/thesaurus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://data.gbif.org/thesaurus"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:dcmitype="http://purl.org/dc/dcmitype/"
    targetNamespace="http://data.gbif.org/thesaurus"
    elementFormDefault="qualified">
    <xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
<xs:element name="thesaurus">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="concept" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
    <xs:element name="concept">
        <xs:complexType>
            
            <xs:sequence>
                <!-- Many titles per language for synonyms -->
                <xs:element name="accepted">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="term" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- Many titles per language for synonyms -->
                <xs:element name="synonym">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="term" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="dc:identifier" use="required"/>
            <xs:attribute ref="dc:issued" use="required"/>
            <xs:attribute ref="dc:type" use="required"/>
            <xs:anyAttribute processContents="lax"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="term">
        <xs:complexType>
            <xs:attribute ref="dc:title" use="required"/>
            <xs:attribute ref="dc:lang" use="optional"/>
            <xs:attribute ref="dc:source" use="required"/>
            <xs:attribute ref="dc:relation" use="optional"/>
            <xs:attribute ref="dc:created" use="required"/>
            <xs:attribute ref="dc:modified" use="required"/>  
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gbif/ipt/trunk/gbif-providertool/db/thesaurus_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<thesaurus xmlns:dc="http://purl.org/dc/terms/"
    xmlns="http://data.gbif.org/thesaurus"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://data.gbif.org/thesaurus  thesaurus.xsd">
    <concept dc:identifier="http://iso.org/3166#US" iso3Digit="USA" iso2Digit="US" dc:type="http://iso.org/3166#country" dc:issued="2006-05-04T18:13:51.0Z">
        <accepted>
            <term dc:title="United States of America" dc:lang="en" dc:source="source0" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Vereinigte Staaten von Amerika" dc:lang="de" dc:source="source1" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </accepted>
        <synonym>
            <term dc:title="USA" dc:lang="en" dc:source="source3" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="US of A" dc:lang="en" dc:source="source4" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="United States" dc:lang="en" dc:source="source5" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </synonym>
    </concept>

    <concept dc:identifier="http://rs.tdwg.org/ontology/voc/TaxonRank#Species" dc:type="http://rs.tdwg.org/ontology/voc/TaxonRank" dc:issued="2006-05-04T18:13:51.0Z">
        <accepted>
            <term dc:title="Species" dc:lang="en" dc:source="source12" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Art" dc:lang="de" dc:source="source13" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </accepted>
        <synonym>
            <term dc:title="Spec." dc:lang="en" dc:source="source15" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Sp." dc:lang="en" dc:source="source16" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
            <term dc:title="Spec" dc:lang="en" dc:source="source17" dc:created="2006-05-04T18:13:51.0Z" dc:modified="2006-05-04T18:13:51.0Z"/>
        </synonym>
    </concept>
</thesaurus>
