=== gbif/ipt/trunk/gbif-providertool/resources/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ipt.gbif.org/extension/" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="extension">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="0">
                            <xs:element name="vocabulary" type="xs:anyURI"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="namespace" type="xs:string" use="required"/>
                        <xs:attribute name="qualName" type="xs:string" use="required"/>
                        <xs:attribute name="group" type="xs:string" use="optional"/>
                        <xs:attribute name="columnLength" type="xs:positiveInteger" default="128"/>
                        <xs:attribute name="link" type="xs:anyURI"/>
                        <xs:attribute name="required" type="xs:boolean" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="title" type="xs:string"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="namespace" type="xs:string" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Sample"/>
                        <xs:enumeration value="Taxon"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="link" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gbif/ipt/trunk/gbif-providertool/resources/extensions/ecat/gna_vernacular.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	This defines the extension for defining vernacular names as extensions to a Taxon core object
	
	This has the dependency on thesauri:
	- language code:  http://gbrds.gbif.org/resources/thesauri/lang.xml
	- country codes:  http://gbrds.gbif.org/resources/thesauri/country-code.xml
	
-->
<extension xmlns="http://ipt.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ipt.gbif.org/extension/ http://gbrds.gbif.org/resources/schemas/extension.xsd" 
    title="GNA Vernacular Names" name="VernacularName" namespace="http://rs.gbif.org/terms/1.0">
    
    <property name="vernacularName" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/vernacularName" required="true"/>
    <property name="source" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/source" />
    <property name="language" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/language" thesaurus="http://gbrds.gbif.org/resources/thesauri/lang.xml" columnLength="2" required="true"/>
    <property name="temporal" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/temporal" />
    
    <property name="locationID" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/locationID" />
    <property name="locality" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/locality" />
    <property name="countryCode" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/countryCode" thesaurus="http://gbrds.gbif.org/resources/thesauri/country-code.xml" columnLength="2"/>

    <property name="sex" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/sex" columnLength="64"/>
    <property name="lifeStage" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/lifeStage" />
    <property name="organismPart" namespace="http://rs.gbif.org/terms/1.0" qualName="http://rs.gbif.org/terms/1.0/organismPart" />
    
    <property name="isPlural" namespace="http://rs.gbif.org/terms/1.0" qualName="http://rs.gbif.org/terms/1.0/isPlural" columnLength="5" />
    <property name="isPreferredName" namespace="http://rs.gbif.org/terms/1.0" qualName="http://rs.gbif.org/terms/1.0/isPreferredName" columnLength="5"/>
</extension>

=== gbif/ipt/trunk/gbif-providertool/resources/extensions/sampleAttribute.xml
<?xml version="1.0" encoding="UTF-8"?>

<extension xmlns="http://ipt.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://gbrds.gbif.org/resources/schemas/extension.xsd" 
    title="Sample Attribute" name="SampleAttribute" namespace="http://rs.tdwg.org/dwc/terms/">
    <property name="SampleAttributeID" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeID" />
    <property name="SampleAttributeType" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeType" />
    <property name="SampleAttributeValue" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeValue" />
    <property name="SampleAttributeAccuracy" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeAccuracy" />
    <property name="SampleAttributeUnit" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeUnit" />
    <property name="SampleAttributeDeterminedDate" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeDeterminedDate" />
    <property name="SampleAttributeDeterminedBy" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeDeterminedBy" />
    <property name="SampleAttributeRemarks" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/SampleAttributeRemarks" />
</extension>

=== gbif/ipt/trunk/gbif-providertool/resources/extensions/identificationHistory.xml
<?xml version="1.0" encoding="UTF-8"?>

<extension xmlns="http://ipt.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="../extension.xsd" 
    title="Identification History" name="Identification" namespace="http://rs.tdwg.org/dwc/terms/">
    <property name="NomenclaturalCode" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/NomenclaturalCode"/>
    <property name="ScientificName" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/ScientificName" required="true"/>
    <property name="TaxonAccordingTo" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/TaxonAccordingTo"/>    
    <property name="IdentifiedBy" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentifiedBy" />
    <property name="DateIdentified" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/DateIdentified" />
    <property name="IdentificationReferences" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentificationReferences" />
    <property name="IdentificationRemarks" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentificationRemarks" />
    <property name="IdentificationQualifier" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentificationQualifier" />
    <property name="TypeStatus" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/TypeStatus" />
</extension>
