=== gbif/ipt/gbif-providertool/resources/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dc="http://purl.org/dc/terms/" targetNamespace="http://ipt.gbif.org/extension/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://purl.org/dc/terms/" schemaLocation="dc.xsd"/>
    <xs:element name="extension">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="property" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="0">
                            <xs:element name="vocabulary" type="xs:anyURI"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="namespace" type="xs:string" use="required"/>
                        <xs:attribute name="qualName" type="xs:string" use="required"/>
                        <xs:attribute name="group" type="xs:string" use="optional"/>
                        <xs:attribute name="columnLength" type="xs:positiveInteger" default="128"/>
						<xs:attribute ref="dc:description" use="optional">
							<xs:annotation><xs:documentation>A URL acting as documentation for the property</xs:documentation></xs:annotation>
						</xs:attribute>
                        <xs:attribute name="thesaurus" type="xs:anyURI"/>
                        <xs:attribute name="required" type="xs:boolean" default="false"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="title" type="xs:string"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="namespace" type="xs:string" use="required"/>
			<xs:attribute ref="dc:description" use="optional">
				<xs:annotation><xs:documentation>A URL acting as documentation for the entire vocabulary</xs:documentation></xs:annotation>
			</xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gbif/ipt/branches/gbif-ipt-lite/gbif-providertool/resources/extensions/vernacularName2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	This defines the extension for defining vernacular names as extensions to a Taxon core object
	An instance of this represents a http://rs.gbif.org/ecat/class/VernacularName
	
	This has the dependency on thesauri:
		- language code:  http://rs.gbif.org/thesaurus/languageCode.xml
-->
<extension xmlns="http://ipt.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ipt.gbif.org/extension/ http://gbrds.gbif.org/resources/schemas/extension.xsd" 
    title="Vernacular Name 2" name="VernacularName" namespace="http://rs.gbif.org/ecat/terms/v2">
    
    <property name="vernacularName" namespace="http://rs.gbif.org/ecat/terms/" qualName="http://rs.gbif.org/ecat/terms/vernacularName" required="true"/>
    <property name="language" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/language" thesaurus="http://gbrds.gbif.org/resources/thesauri/lang.xml" columnLength="3"/>
    <property name="area" namespace="http://rs.gbif.org/ecat/terms/" qualName="http://rs.gbif.org/thesaurus/area" />
    <property name="areaSource" namespace="http://rs.gbif.org/ecat/terms/" qualName="http://rs.gbif.org/thesaurus/areaSource" columnLength="128"/>
    <property name="preferred" namespace="http://rs.gbif.org/ecat/terms/" qualName="http://rs.gbif.org/ecat/terms/preferred" columnLength="1"/>
    
    <property name="Continent" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/Continent" columnLength="64"/>
    <property name="Waterbody" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/Waterbody" columnLength="128"/>
    <property name="IslandGroup" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IslandGroup" columnLength="128"/>
    <property name="Island" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/Island" columnLength="128"/>
    <property name="Country" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/Country" columnLength="128"/>
    <property name="CountryCode" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/CountryCode" thesaurus="http://gbrds.gbif.org/resources/thesauri/country-code.xml" columnLength="3"/>
    <property name="StateProvince" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/StateProvince" columnLength="128"/>
    <property name="County" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/County" columnLength="128"/>
    <property name="Locality" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/Locality" columnLength="1000"/>
</extension>

=== gbif/ipt/branches/gbif-ipt-lite/gbif-providertool/resources/extensions/identificationHistory.xml
<?xml version="1.0" encoding="UTF-8"?>
<extension xmlns="http://ipt.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ipt.gbif.org/extension/ http://gbrds.gbif.org/resources/schemas/extension.xsd" 
    title="Identification History" name="Identification" namespace="http://rs.tdwg.org/dwc/terms/">
    <property name="NomenclaturalCode" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/NomenclaturalCode"/>
    <property name="ScientificName" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/ScientificName" required="true"/>
    <property name="TaxonAccordingTo" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/TaxonAccordingTo"/>    
    <property name="IdentifiedBy" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentifiedBy" />
    <property name="DateIdentified" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/DateIdentified" />
    <property name="IdentificationReferences" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentificationReferences" />
    <property name="IdentificationRemarks" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentificationRemarks" />
    <property name="IdentificationQualifier" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/IdentificationQualifier" />
    <property name="TypeStatus" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/TypeStatus" />
</extension>

=== gbif/ipt/deprecated/ipt-1.0-RC3/resources/extensions/eventAttribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<extension xmlns="http://ipt.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ipt.gbif.org/extension/ http://gbrds.gbif.org/resources/schemas/extension.xsd" 
    title="Event Attribute" name="EventAttribute" namespace="http://rs.tdwg.org/dwc/terms/">
    <property name="EventAttributeID" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeID" />
    <property name="EventAttributeType" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeType" />
    <property name="EventAttributeValue" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeValue" />
    <property name="EventAttributeAccuracy" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeAccuracy" />
    <property name="EventAttributeUnit" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeUnit" />
    <property name="EventAttributeDeterminedDate" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeDeterminedDate" />
    <property name="EventAttributeDeterminedBy" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeDeterminedBy" />
    <property name="EventAttributeRemarks" namespace="http://rs.tdwg.org/dwc/terms/" qualName="http://rs.tdwg.org/dwc/terms/EventAttributeRemarks" />
</extension>

=== gbif/ipt/deprecated/ipt-1.0RC1/gbif-providertool/resources/extensions/resources.xml
<?xml version="1.0" encoding="UTF-8"?>
<extension xmlns="http://ipt.gbif.org/extension/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ipt.gbif.org/extension/ http://gbrds.gbif.org/resources/schemas/extension.xsd" 
    title="Related Resources" name="relation" namespace="http://purl.org/dc/terms/">
    <property name="abstract" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/abstract"/>
    <property name="contributor" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/contributor"/>
    <property name="coverage" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/coverage"/>
    <property name="creator" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/creator"/>
    <property name="created" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/created"/>
    <property name="description" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/description"/>
    <property name="format" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/format"/>
    <property name="identifier" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/identifier"/>
    <property name="issued" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/issued"/>
    <property name="isVersionOf" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/isVersionOf"/>
    <property name="language" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/language"/>
    <property name="medium" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/medium"/>
    <property name="modified" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/modified"/>    
    <property name="publisher" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/publisher"/>
    <property name="relation" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/relation"/>
    <property name="rights" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/rights"/>
    <property name="source" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/source"/>
    <property name="spatial" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/spatial"/>
    <property name="subject" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/subject"/>
    <property name="temporal" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/temporal"/>
    <property name="title" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/title"/>
    <property name="type" namespace="http://purl.org/dc/terms/" qualName="http://purl.org/dc/terms/type"/>
        
</extension>
